### ISSUE TITLE
Still cant get it to work..

### ISSUE THREAD

**Issue by ghost** [cas--/deluge-ipstatusbar#1]
I still cant get it to work.. The status bar is the thing on the very bottom of the window right?

When I try install it from github it takes about 2 minutes to load the plugin when you press apply and then it either crashes or just doesnt do anything at all.

I really dont know what im doing wrong.
Im using: Windows 10, latest version of deluge.

**Comment by cas--** [comment]
I have new code to release that should work, I'll get around to it soon

**Comment by ghost** [comment]
Okay thanks! Im using the 2.7 build by the way

**Comment by cas--** [comment]
Should be fixed now in 0.2: https://github.com/cas--/deluge-ipstatusbar/releases

**Comment by ghost** [comment]
Works perfectly! Thanks :)

**Comment by ghost** [comment]
Is there a way to force the ip to update? So I can check if deluge is bypassing my proxy

**Comment by cas--** [comment]
No you can't force check with libtorrent but it will update if it changes. 

I perhaps could do something with [ipgetter](https://github.com/phoemur/ipgetter) module which is a more robust ip website checker.
